### ISSUE TITLE
load refuses to load non-x86_64 elfs

### ISSUE THREAD

**Issue by Trolldemorted** [gz/rust-elfloader#13]
because of the check in `is_loadable`:

https://github.com/gz/rust-elfloader/blob/431cca144e80443ed83a31c7818dc65b973a8199/src/lib.rs#L306-L328

Is that check necessary? I have to initialize memory regions in an arm emulator and would like to use elfloader for that (I assumed it parses arm64-elfs correctly).

**Comment by gz** [comment]
Hi @Trolldemorted, When I wrote the code and up until now we were only running it on x86-64 machines. Therefore the check -- it could definitely work on other architectures out of the box, or you could run into some problems (for example due to hard-coded endianness assumptions etc.).

You could just go ahead and remove/adapt the check for now and see how far you come with this. Feel free to send a pull-request or open further issues if you get stuck

**Comment by Trolldemorted** [comment]
I have removed the check locally, and am able to load the memory sections into my emulator like a charm.

Do you want to keep that check or can we just dump it?

**Comment by gz** [comment]
@Trolldemorted Awesome, feel free to send a pull request that removes it then
